import { DataTypes } from 'sequelize';
import sequelize from '../base-dato/Postgresql.js';
const common = { timestamps: false, freezeTableName: true };
const CajaBanco = sequelize.define('CajaBanco', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, fecha: DataTypes.DATEONLY, saldo_inicial: DataTypes.DECIMAL(14,2), saldo_actual: DataTypes.DECIMAL(14,2), estado: DataTypes.ENUM('ABIERTA','CERRADA'), usuario_id: DataTypes.INTEGER, usuario_nombre: DataTypes.STRING(150), observacion: DataTypes.TEXT, activo: DataTypes.BOOLEAN, created_at: DataTypes.DATE, updated_at: DataTypes.DATE, cerrado_en: DataTypes.DATE, cerrado_por_id: DataTypes.INTEGER, cerrado_por_nombre: DataTypes.STRING(150) }, { tableName: 'cajas_banco', ...common });
const CajaChica = sequelize.define('CajaChica', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, fecha: DataTypes.DATEONLY, monto_inicial: DataTypes.DECIMAL(14,2), monto_actual: DataTypes.DECIMAL(14,2), estado: DataTypes.ENUM('ABIERTA','CERRADA'), usuario_id: DataTypes.INTEGER, usuario_nombre: DataTypes.STRING(150), observacion: DataTypes.TEXT, activo: DataTypes.BOOLEAN, caja_banco_id: DataTypes.INTEGER, created_at: DataTypes.DATE, updated_at: DataTypes.DATE, cerrado_en: DataTypes.DATE, cerrado_por_id: DataTypes.INTEGER, cerrado_por_nombre: DataTypes.STRING(150) }, { tableName: 'cajas_chicas', ...common });
const MovimientoChica = sequelize.define('MovimientoChica', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, caja_chica_id: DataTypes.INTEGER, fecha: DataTypes.DATE, tipo: DataTypes.ENUM('INGRESO','EGRESO'), descripcion: DataTypes.STRING(255), monto: DataTypes.DECIMAL(14,2), saldo_anterior: DataTypes.DECIMAL(14,2), saldo_nuevo: DataTypes.DECIMAL(14,2), factura_id: DataTypes.INTEGER, usuario_id: DataTypes.INTEGER, usuario_nombre: DataTypes.STRING(150), referencia: DataTypes.STRING(100), created_at: DataTypes.DATE }, { tableName: 'movimientos_cajas_chicas', ...common });
const MovimientoBanco = sequelize.define('MovimientoBanco', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, caja_banco_id: DataTypes.INTEGER, fecha: DataTypes.DATE, tipo: DataTypes.ENUM('INGRESO','EGRESO'), categoria: DataTypes.ENUM('CIERRE_CAJA_CHICA','TRANSFERENCIA_CLIENTE','PAGO_TRABAJADOR','PAGO_PROVEEDORES','OTRO_INGRESO','OTRO_EGRESO'), monto: DataTypes.DECIMAL(14,2), saldo_anterior: DataTypes.DECIMAL(14,2), saldo_nuevo: DataTypes.DECIMAL(14,2), descripcion: DataTypes.STRING(255), referencia_id: DataTypes.INTEGER, venta_id: DataTypes.INTEGER, usuario_id: DataTypes.INTEGER, usuario_nombre: DataTypes.STRING(150), created_at: DataTypes.DATE }, { tableName: 'movimientos_cajas_banco', ...common });
const Cuenta = sequelize.define('Cuenta', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, fecha: DataTypes.DATEONLY, tipo: DataTypes.ENUM('PAGAR','COBRAR'), tipo_cuenta_por_pagar: DataTypes.ENUM('Deuda','Prestamo'), monto_total: DataTypes.DECIMAL(14,2), monto_abonado: DataTypes.DECIMAL(14,2), saldo: DataTypes.DECIMAL(14,2), estado: DataTypes.ENUM('ACTIVA','CANCELADA'), observacion: DataTypes.TEXT, tercero_nombre: DataTypes.STRING(150), tercero_id: DataTypes.INTEGER, usuario_id: DataTypes.INTEGER, sucursal_id: DataTypes.INTEGER, caja_banco_id: DataTypes.INTEGER, created_at: DataTypes.DATE, updated_at: DataTypes.DATE }, { tableName: 'cuentas', ...common });
export { CajaBanco, CajaChica, MovimientoChica, MovimientoBanco, Cuenta };
