// facturacion-servicio/src/infraestructura/modelos/Modelos.js
import { DataTypes } from 'sequelize';
import sequelize from '../base-dato/Postgresql.js';
import OperacionFinanciera from './ModeloOperacionFinanciera.js';
const common = { timestamps: false, freezeTableName: true };
const Factura = sequelize.define('Factura', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, id_personalizado: DataTypes.STRING(10), cliente_id: { type: DataTypes.INTEGER, allowNull: false }, historial_clinico_id: DataTypes.INTEGER, cliente_nombre: DataTypes.STRING(200), historial_snapshot: DataTypes.JSONB, subtotal: DataTypes.DECIMAL(14,2), subtotal_bruto: DataTypes.DECIMAL(14,2), iva: DataTypes.DECIMAL(14,2), total: DataTypes.DECIMAL(14,2), metodo_pago: { type: DataTypes.STRING(30), allowNull: false }, codigo_transferencia: DataTypes.STRING(100), es_credito: DataTypes.BOOLEAN, abonado: DataTypes.DECIMAL(14,2), saldo_pendiente: DataTypes.DECIMAL(14,2), estado_credito: DataTypes.ENUM('ACTIVO','CANCELADO'), tipo_venta: DataTypes.ENUM('CONTADO','CREDITO'), estado_pago: DataTypes.ENUM('PAGADA','PENDIENTE','ANULADA'), observacion: DataTypes.TEXT, fecha: DataTypes.DATE, usuario_id: DataTypes.INTEGER, sucursal_id: DataTypes.INTEGER, sucursal_nombre: DataTypes.STRING(100), estado_inventario: DataTypes.STRING(30), created_at: DataTypes.DATE, updated_at: DataTypes.DATE, deleted_at: DataTypes.DATE }, { tableName: 'facturas', ...common });
const DetalleFactura = sequelize.define('DetalleFactura', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, factura_id: DataTypes.INTEGER, producto_id: DataTypes.INTEGER, catalogo_item_id: DataTypes.INTEGER, nombre: { type: DataTypes.STRING(150), allowNull: false }, tipo: DataTypes.STRING(60), codigo: DataTypes.STRING(50), id_interno: DataTypes.INTEGER, cantidad: DataTypes.INTEGER, precio_unitario: DataTypes.DECIMAL(14,2), total: DataTypes.DECIMAL(14,2), es_servicio: DataTypes.BOOLEAN }, { tableName: 'detalle_facturas', ...common });
const Deuda = sequelize.define('Deuda', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, factura_id: DataTypes.INTEGER, factura_id_personalizado: DataTypes.STRING(10), cliente_id: DataTypes.INTEGER, cliente_nombre: { type: DataTypes.STRING(200), allowNull: false }, metodo_pago: { type: DataTypes.STRING(30), allowNull: false }, cliente_telefono: DataTypes.STRING(30), fecha_pago: DataTypes.DATE, monto_pagado: DataTypes.DECIMAL(14,2), total_factura: DataTypes.DECIMAL(14,2), saldo_restante: DataTypes.DECIMAL(14,2), codigo_transferencia: DataTypes.STRING(100), ultimos_cuatro_tarjeta: DataTypes.STRING(4), estado_pago: DataTypes.ENUM('PAGADA','PENDIENTE','ANULADA'), es_credito: DataTypes.BOOLEAN, usuario_id: DataTypes.INTEGER, created_at: DataTypes.DATE }, { tableName: 'facturas_deudas', ...common });
const VentaTarjeta = sequelize.define('VentaTarjeta', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, factura_id: DataTypes.INTEGER, factura_id_personalizado: DataTypes.STRING(10), cliente_id: DataTypes.INTEGER, cliente_nombre: DataTypes.STRING(200), fecha_venta: DataTypes.DATE, monto_total: DataTypes.DECIMAL(14,2), monto_recibido: DataTypes.DECIMAL(14,2), saldo_pendiente: DataTypes.DECIMAL(14,2), estado: DataTypes.ENUM('PENDIENTE','PROCESANDO','PARCIALMENTE_ACREDITADA','ACREDITADA','RECHAZADA','ANULADA','LEGACY_LIQUIDADA'), ultimos_cuatro_tarjeta: DataTypes.STRING(4), banco: DataTypes.STRING(80), numero_lote: DataTypes.STRING(50), observacion: DataTypes.TEXT, cuenta_banco_id: DataTypes.INTEGER, fecha_ultima_acreditacion: DataTypes.DATE, comision_acumulada: DataTypes.DECIMAL(14,2), retencion_acumulada: DataTypes.DECIMAL(14,2), monto_bruto_acreditado: DataTypes.DECIMAL(14,2), monto_neto_acreditado: DataTypes.DECIMAL(14,2), created_at: DataTypes.DATE, updated_at: DataTypes.DATE }, { tableName: 'ventas_tarjeta', ...common });
const AbonoTarjeta = sequelize.define('AbonoTarjeta', { id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true }, venta_tarjeta_id: DataTypes.INTEGER, fecha: DataTypes.DATE, monto: DataTypes.DECIMAL(14,2), observacion: DataTypes.TEXT, monto_bruto: DataTypes.DECIMAL(14,2), comision: DataTypes.DECIMAL(14,2), retencion: DataTypes.DECIMAL(14,2), monto_neto: DataTypes.DECIMAL(14,2), banco: DataTypes.STRING(80), numero_lote: DataTypes.STRING(50), numero_autorizacion: DataTypes.STRING(100), voucher: DataTypes.STRING(100), fecha_acreditacion: DataTypes.DATE, cuenta_banco_id: DataTypes.INTEGER, operacion_id: DataTypes.UUID, idempotency_key: { type: DataTypes.STRING(255), unique: true }, usuario_id: DataTypes.INTEGER, usuario_nombre: DataTypes.STRING(150), trace_id: DataTypes.STRING(100), estado: DataTypes.ENUM('PENDIENTE','APLICADO','ERROR','REVERTIDO'), created_at: DataTypes.DATE }, { tableName: 'abonos_ventas_tarjeta', ...common });
export {
  Factura,
  DetalleFactura,
  Deuda,
  VentaTarjeta,
  AbonoTarjeta,
  OperacionFinanciera,
};
