import { Op } from 'sequelize';
import sequelize from '../base-dato/Postgresql.js';
import { CajaBanco, CajaChica, MovimientoChica, MovimientoBanco, Cuenta } from '../modelos/Modelos.js';
const modelos = { 'cajas-banco': CajaBanco, 'cajas-chicas': CajaChica, 'movimientos-banco': MovimientoBanco, 'movimientos-chicas': MovimientoChica, cuentas: Cuenta };
const cajas = { banco: { caja: CajaBanco, movimiento: MovimientoBanco, saldo: 'saldo_actual', inicial: 'saldo_inicial', fk: 'caja_banco_id' }, chica: { caja: CajaChica, movimiento: MovimientoChica, saldo: 'monto_actual', inicial: 'monto_inicial', fk: 'caja_chica_id' } };
export default class CajaAdaptador {
  async listar(recurso, { estado = null, cajaId = null, limit = 20, offset = 0 } = {}) { const Model = modelos[recurso]; if (!Model) return { estado: 'error', resultado: 'Recurso inválido' }; const where = {}; if (estado && Model.rawAttributes.estado) where.estado = estado; if (cajaId && Model.rawAttributes.caja_banco_id) where.caja_banco_id = cajaId; if (cajaId && Model.rawAttributes.caja_chica_id) where.caja_chica_id = cajaId; return { estado: 'ok', resultado: await Model.findAll({ where, order: [['id','DESC']], limit: Math.min(Number(limit)||20,100), offset: Math.max(Number(offset)||0,0) }) }; }
  async obtener(recurso, id) { const Model = modelos[recurso]; if (!Model) return { estado: 'error', resultado: 'Recurso inválido' }; const item = await Model.findByPk(id); return item ? { estado: 'ok', resultado: item } : { estado: 'error', resultado: 'No encontrado' }; }
  async crear(recurso, datos) { const Model = modelos[recurso]; if (!Model) return { estado: 'error', resultado: 'Recurso inválido' }; try { const ahora = new Date(); return { estado: 'ok', resultado: await Model.create({ ...datos, created_at: datos.created_at || ahora, updated_at: datos.updated_at || ahora }) }; } catch (error) { return { estado: 'error', resultado: error.message }; } }
  async actualizar(recurso, id, datos) { const Model = modelos[recurso]; if (!Model) return { estado: 'error', resultado: 'Recurso inválido' }; const [count] = await Model.update({ ...datos, updated_at: new Date() }, { where: { id } }); return count ? { estado: 'ok', resultado: 'Actualizado correctamente' } : { estado: 'error', resultado: 'No encontrado' }; }
  async eliminar(recurso, id) { const Model = modelos[recurso]; if (!Model) return { estado: 'error', resultado: 'Recurso inválido' }; const count = await Model.destroy({ where: { id } }); return count ? { estado: 'ok', resultado: 'Eliminado correctamente' } : { estado: 'error', resultado: 'No encontrado' }; }
  async abrir(tipo, datos) { const config = cajas[tipo]; const where = { estado: 'ABIERTA', activo: true }; const abierta = await config.caja.findOne({ where }); if (abierta) return { estado: 'error', resultado: 'Ya existe una caja abierta' }; const ahora = new Date(); const inicial = Number(datos.saldoInicial ?? datos.montoInicial ?? 0); return { estado: 'ok', resultado: await config.caja.create({ fecha: datos.fecha || ahora, [config.inicial]: inicial, [config.saldo]: inicial, estado: 'ABIERTA', activo: true, usuario_id: datos.usuarioId, usuario_nombre: datos.usuarioNombre, observacion: datos.observacion, created_at: ahora, updated_at: ahora }) }; }
  async cerrar(tipo, id, datos) { const config = cajas[tipo]; const [count] = await config.caja.update({ estado: 'CERRADA', cerrado_en: new Date(), cerrado_por_id: datos.usuarioId, cerrado_por_nombre: datos.usuarioNombre, updated_at: new Date() }, { where: { id, estado: 'ABIERTA' } }); return count ? { estado: 'ok', resultado: 'Caja cerrada correctamente' } : { estado: 'error', resultado: 'Caja no encontrada o ya cerrada' }; }
  async movimiento(tipo, datos) { const config = cajas[tipo]; const transaction = await sequelize.transaction(); try { const caja = await config.caja.findOne({ where: { id: datos.cajaId, estado: 'ABIERTA', activo: true }, transaction, lock: transaction.LOCK.UPDATE }); if (!caja) { await transaction.rollback(); return { estado: 'error', resultado: 'Caja no encontrada o cerrada' }; } const anterior = Number(caja[config.saldo]); const monto = Number(datos.monto); const nuevo = datos.tipo === 'EGRESO' ? anterior - monto : anterior + monto; if (nuevo < 0) { await transaction.rollback(); return { estado: 'error', resultado: 'Saldo insuficiente' }; } await caja.update({ [config.saldo]: nuevo, updated_at: new Date() }, { transaction }); const movimiento = await config.movimiento.create({ ...datos, [config.fk]: datos.cajaId, fecha: datos.fecha || new Date(), saldo_anterior: anterior, saldo_nuevo: nuevo, created_at: new Date() }, { transaction }); await transaction.commit(); return { estado: 'ok', resultado: movimiento }; } catch (error) { await transaction.rollback(); return { estado: 'error', resultado: error.message }; } }
}
