import { REPORT_PERMISSIONS } from './categories.config';

const filters = {
    fechaDesde: { key: 'fechaDesde', label: 'Fecha desde', type: 'date', queryParam: 'fechaDesde' },
    fechaHasta: { key: 'fechaHasta', label: 'Fecha hasta', type: 'date', queryParam: 'fechaHasta' },
    codigo: { key: 'codigo', label: 'Producto', type: 'product-search', source: 'productos', queryParam: 'codigo' },
    grupo: { key: 'grupo', label: 'Grupo', type: 'entity', source: 'grupos', queryParam: 'grupo' },
    proveedorId: { key: 'proveedorId', label: 'Proveedor', type: 'entity', source: 'proveedores', queryParam: 'proveedorId' },
    sucursalId: { key: 'sucursalId', label: 'Sucursal', type: 'entity', source: 'sucursales', queryParam: 'sucursalId' },
    usuarioId: { key: 'usuarioId', label: 'Usuario', type: 'entity', source: 'usuarios', queryParam: 'usuarioId' },
    clienteId: { key: 'clienteId', label: 'Cliente', type: 'entity', source: 'clientes', queryParam: 'clienteId' },
    estado: {
        key: 'estado',
        label: 'Estado',
        type: 'select',
        queryParam: 'estado',
        options: [
            { value: '', label: 'Todos' },
            { value: 'PAGADA', label: 'Pagada' },
            { value: 'PENDIENTE', label: 'Pendiente' },
        ],
    },
    tipoMovimiento: {
        key: 'tipoMovimiento',
        label: 'Tipo de movimiento',
        type: 'select',
        queryParam: 'tipoMovimiento',
        options: [
            { value: '', label: 'Todos' },
            { value: 'INVENTARIO_INICIAL', label: 'Inventario inicial' },
            { value: 'COMPRA', label: 'Compra' },
            { value: 'VENTA', label: 'Venta' },
            { value: 'DEVOLUCION_CLIENTE', label: 'Devolución de cliente' },
            { value: 'DEVOLUCION_PROVEEDOR', label: 'Devolución a proveedor' },
            { value: 'EGRESO', label: 'Egreso' },
            { value: 'AJUSTE', label: 'Ajuste' },
            { value: 'TRANSFERENCIA_ENTRADA', label: 'Transferencia de entrada' },
            { value: 'TRANSFERENCIA_SALIDA', label: 'Transferencia de salida' },
            { value: 'ANULACION_VENTA', label: 'Anulación de venta' },
            { value: 'ANULACION_COMPRA', label: 'Anulación de compra' },
            { value: 'ANULACION_EGRESO', label: 'Anulación de egreso' },
            { value: 'REVALORIZACION', label: 'Revalorización' },
            { value: 'COMPENSACION', label: 'Compensación' },
        ],
    },
};

const actions = ['refresh', 'exportExcel', 'exportPdf', 'clearFilters'];
const exportable = { pdf: true, excel: true, csv: false };

const createReport = (report) => ({
    enabled: true,
    beta: false,
    rememberFilters: true,
    exportable,
    actions,
    summary: [],
    refreshInterval: null,
    filters: [],
    columns: [],
    ...report,
});

export const reportsConfig = {
    inventario: {
        kardex: createReport({
            id: 'kardex',
            category: 'inventario',
            title: 'Kardex',
            shortTitle: 'Kardex',
            description: 'Consulta todos los movimientos del inventario y filtra opcionalmente por producto.',
            endpoint: 'kardex/fecha',
            permission: REPORT_PERMISSIONS.INVENTARIO,
            defaultFilters: { codigo: '', grupo: '', proveedorId: '', usuarioId: '', tipoMovimiento: '', sucursalId: '', fechaDesde: '', fechaHasta: '' },
            summary: [
                { key: 'stockActual', label: 'Stock actual', type: 'number', color: '#1abc9c' },
                { key: 'entradas', label: 'Entradas', type: 'number', color: '#27ae60' },
                { key: 'salidas', label: 'Salidas', type: 'number', color: '#e74c3c' },
                { key: 'costoPromedio', label: 'Costo promedio', type: 'currency', color: '#8e44ad' },
                { key: 'valorInventario', label: 'Valor del inventario', type: 'currency', color: '#f39c12' },
                { key: 'ultimoMovimiento', label: 'Último movimiento', type: 'datetime', color: '#607d8b' },
            ],
            filters: [filters.codigo, filters.grupo, filters.proveedorId, filters.usuarioId, filters.tipoMovimiento, filters.sucursalId, filters.fechaDesde, filters.fechaHasta],
            productFields: [
                { key: 'codigo', label: 'Código' }, { key: 'modelo', label: 'Modelo' }, { key: 'color', label: 'Color' },
                { key: 'grupo', label: 'Grupo' }, { key: 'costo', label: 'Costo', type: 'currency' },
                { key: 'pvp1', label: 'Precio venta', type: 'currency' }, { key: 'stock', label: 'Stock actual', type: 'number' },
                { key: 'proveedor', label: 'Proveedor' }, { key: 'ultimoIngreso', label: 'Último ingreso', type: 'datetime' },
                { key: 'estado', label: 'Estado' },
            ],
            columns: [
                { key: 'fecha', label: 'Fecha' }, { key: 'hora', label: 'Hora' }, { key: 'productoCodigo', label: 'Código' },
                { key: 'productoNombre', label: 'Producto' }, { key: 'grupo', label: 'Grupo' }, { key: 'documento', label: 'Documento' },
                { key: 'tipoMovimiento', label: 'Tipo de movimiento' }, { key: 'detalle', label: 'Detalle' },
                { key: 'entrada', label: 'Entrada', type: 'number', align: 'right' }, { key: 'salida', label: 'Salida', type: 'number', align: 'right' },
                { key: 'stockAnterior', label: 'Stock anterior', type: 'number', align: 'right' }, { key: 'stockActual', label: 'Stock actual', type: 'number', align: 'right' },
                { key: 'costoUnitario', label: 'Costo unitario', type: 'currency', align: 'right' }, { key: 'saldo', label: 'Saldo', type: 'currency', align: 'right' },
                { key: 'usuario', label: 'Usuario' }, { key: 'sucursal', label: 'Sucursal' }, { key: 'observacion', label: 'Observación' },
            ],
        }),
    },
    ventas: {
        'ventas-mas-vendidos': createReport({
            id: 'ventas-mas-vendidos',
            category: 'ventas',
            title: 'Productos más vendidos',
            shortTitle: 'Más vendidos',
            description: 'Consulta los productos con mayor cantidad de unidades vendidas.',
            endpoint: 'ventas/mas-vendidos',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', sucursalId: '', usuarioId: '', clienteId: '' },
            refreshInterval: 60000,
            summary: [{ key: 'facturas', label: 'Facturas', type: 'number', color: '#3498db' }, { key: 'productos', label: 'Productos', type: 'number', color: '#27ae60' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.sucursalId, filters.usuarioId, filters.clienteId],
            columns: [
                { key: 'codigo', label: 'Código' }, { key: 'nombre', label: 'Producto' }, { key: 'cantidad_vendida', label: 'Cantidad vendida', type: 'number', align: 'right' },
                { key: 'total_vendido', label: 'Total vendido', type: 'currency', align: 'right' }, { key: 'stock_actual', label: 'Stock actual', type: 'number', align: 'right' },
            ],
        }),
        'ventas-menos-vendidos': createReport({
            id: 'ventas-menos-vendidos',
            category: 'ventas',
            title: 'Productos menos vendidos',
            shortTitle: 'Menos vendidos',
            description: 'Consulta los productos con menor cantidad de unidades vendidas.',
            endpoint: 'ventas/menos-vendidos',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', sucursalId: '', usuarioId: '', clienteId: '' },
            refreshInterval: 60000,
            summary: [{ key: 'facturas', label: 'Facturas', type: 'number', color: '#3498db' }, { key: 'productos', label: 'Productos', type: 'number', color: '#f39c12' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.sucursalId, filters.usuarioId, filters.clienteId],
            columns: [
                { key: 'codigo', label: 'Código' }, { key: 'nombre', label: 'Producto' }, { key: 'cantidad_vendida', label: 'Cantidad vendida', type: 'number', align: 'right' },
                { key: 'total_vendido', label: 'Total vendido', type: 'currency', align: 'right' }, { key: 'stock_actual', label: 'Stock actual', type: 'number', align: 'right' },
            ],
        }),
        'ventas-generales': createReport({
            id: 'ventas-generales',
            category: 'ventas',
            title: 'Ventas generales',
            shortTitle: 'Ventas',
            description: 'Consulta las ventas realizadas dentro de un rango de fechas.',
            endpoint: 'ventas/general',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', sucursalId: '', usuarioId: '', clienteId: '', estado: '' },
            refreshInterval: 60000,
            summary: [
                { key: 'totalVentas', label: 'Total de ventas', type: 'number', color: '#3498db' },
                { key: 'montoTotal', label: 'Monto total', type: 'currency', color: '#27ae60' },
                { key: 'promedioVenta', label: 'Promedio por venta', type: 'currency', color: '#8e44ad' },
                { key: 'saldoPendiente', label: 'Saldo pendiente', type: 'currency', color: '#e74c3c' },
            ],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.sucursalId, filters.usuarioId, filters.clienteId, filters.estado],
            columns: [
                { key: 'numeroFactura', label: 'Factura', type: 'text' }, { key: 'cliente', label: 'Cliente', type: 'text' }, { key: 'sucursal', label: 'Sucursal', type: 'text' },
                { key: 'usuario', label: 'Usuario', type: 'text' }, { key: 'fecha', label: 'Fecha', type: 'date' }, { key: 'subtotal', label: 'Subtotal', type: 'currency' },
                { key: 'iva', label: 'IVA', type: 'currency' }, { key: 'total', label: 'Total', type: 'currency' }, { key: 'abonado', label: 'Abonado', type: 'currency' },
                { key: 'saldoPendiente', label: 'Saldo pendiente', type: 'currency' }, { key: 'estado', label: 'Estado', type: 'text' },
            ],
        }),
        'ventas-fecha': createReport({
            id: 'ventas-fecha',
            category: 'ventas',
            title: 'Ventas por rango de fechas',
            shortTitle: 'Ventas por fecha',
            description: 'Consulta las ventas filtradas y consolidadas por periodo.',
            endpoint: 'ventas/fecha',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', sucursalId: '', usuarioId: '', clienteId: '', estado: '' },
            refreshInterval: 60000,
            summary: [{ key: 'ventas', label: 'Ventas', type: 'number', color: '#3498db' }, { key: 'total', label: 'Total vendido', type: 'currency', color: '#27ae60' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.sucursalId, filters.usuarioId, filters.clienteId, filters.estado],
            columns: [
                { key: 'id_personalizado', label: 'Factura' }, { key: 'cliente_nombre', label: 'Cliente' }, { key: 'total', label: 'Total', type: 'currency', align: 'right' },
                { key: 'abonado', label: 'Abonado', type: 'currency', align: 'right' }, { key: 'saldo_pendiente', label: 'Saldo pendiente', type: 'currency', align: 'right' }, { key: 'fecha', label: 'Fecha', type: 'datetime' },
            ],
        }),
        'ventas-sucursal': createReport({
            id: 'ventas-sucursal',
            category: 'ventas',
            title: 'Ventas por sucursal',
            shortTitle: 'Por sucursal',
            description: 'Consulta las ventas agrupadas por sucursal.',
            endpoint: 'ventas/sucursal',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', sucursalId: '' },
            refreshInterval: 60000,
            summary: [{ key: 'ventas', label: 'Ventas', type: 'number', color: '#3498db' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.sucursalId],
            columns: [
                { key: 'sucursal_nombre', label: 'Sucursal' }, { key: 'ventas', label: 'Ventas', type: 'number', align: 'right' }, { key: 'total', label: 'Total', type: 'currency', align: 'right' },
                { key: 'abonado', label: 'Abonado', type: 'currency', align: 'right' }, { key: 'saldo_pendiente', label: 'Saldo pendiente', type: 'currency', align: 'right' },
            ],
        }),
        'ventas-usuario': createReport({
            id: 'ventas-usuario',
            category: 'ventas',
            title: 'Ventas por usuario',
            shortTitle: 'Por usuario',
            description: 'Consulta las ventas agrupadas por usuario.',
            endpoint: 'ventas/usuario',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', usuarioId: '' },
            refreshInterval: 60000,
            summary: [{ key: 'ventas', label: 'Ventas', type: 'number', color: '#3498db' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.usuarioId],
            columns: [
                { key: 'usuario_nombre', label: 'Usuario' }, { key: 'ventas', label: 'Ventas', type: 'number', align: 'right' }, { key: 'total', label: 'Total', type: 'currency', align: 'right' },
                { key: 'abonado', label: 'Abonado', type: 'currency', align: 'right' }, { key: 'saldo_pendiente', label: 'Saldo pendiente', type: 'currency', align: 'right' },
            ],
        }),
        'ventas-cliente': createReport({
            id: 'ventas-cliente',
            category: 'ventas',
            title: 'Ventas por cliente',
            shortTitle: 'Por cliente',
            description: 'Consulta las ventas agrupadas por cliente.',
            endpoint: 'ventas/cliente',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', clienteId: '' },
            refreshInterval: 60000,
            summary: [{ key: 'ventas', label: 'Ventas', type: 'number', color: '#3498db' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.clienteId],
            columns: [
                { key: 'cliente_nombre', label: 'Cliente' }, { key: 'ventas', label: 'Ventas', type: 'number', align: 'right' }, { key: 'total', label: 'Total', type: 'currency', align: 'right' },
                { key: 'abonado', label: 'Abonado', type: 'currency', align: 'right' }, { key: 'saldo_pendiente', label: 'Saldo pendiente', type: 'currency', align: 'right' },
            ],
        }),
        'utilidad-ventas': createReport({
            id: 'utilidad-ventas',
            category: 'ventas',
            title: 'Utilidad por ventas',
            shortTitle: 'Utilidad',
            description: 'Compara el valor de venta, costo y utilidad obtenida.',
            endpoint: 'utilidad/ventas',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', sucursalId: '', usuarioId: '' },
            refreshInterval: 60000,
            summary: [{ key: 'venta', label: 'Ventas', type: 'currency', color: '#3498db' }, { key: 'costo', label: 'Costo', type: 'currency', color: '#e67e22' }, { key: 'utilidad', label: 'Utilidad', type: 'currency', color: '#27ae60' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.sucursalId, filters.usuarioId],
            columns: [
                { key: 'id_personalizado', label: 'Factura' }, { key: 'fecha', label: 'Fecha', type: 'datetime' }, { key: 'venta', label: 'Venta', type: 'currency', align: 'right' },
                { key: 'costo', label: 'Costo', type: 'currency', align: 'right' }, { key: 'utilidad', label: 'Utilidad', type: 'currency', align: 'right' },
            ],
        }),
        'cuentas-cobrar': createReport({
            id: 'cuentas-cobrar',
            category: 'ventas',
            title: 'Estado de cuentas por cobrar',
            shortTitle: 'Cuentas por cobrar',
            description: 'Consulta las facturas que mantienen un saldo pendiente de pago.',
            endpoint: 'cuentas-cobrar/estado',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', clienteId: '' },
            refreshInterval: 60000,
            summary: [{ key: 'facturas', label: 'Facturas pendientes', type: 'number', color: '#f39c12' }, { key: 'saldo_total', label: 'Saldo total', type: 'currency', color: '#e74c3c' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.clienteId],
            columns: [
                { key: 'factura_id_personalizado', label: 'Factura' }, { key: 'cliente_nombre', label: 'Cliente' }, { key: 'total', label: 'Total', type: 'currency', align: 'right' },
                { key: 'abonado', label: 'Abonado', type: 'currency', align: 'right' }, { key: 'saldo_pendiente', label: 'Saldo pendiente', type: 'currency', align: 'right' }, { key: 'fecha', label: 'Fecha', type: 'datetime' },
            ],
        }),
    },
    compras: {
        'compras-proveedor': createReport({
            id: 'compras-proveedor',
            category: 'compras',
            title: 'Compras por proveedor',
            shortTitle: 'Por proveedor',
            description: 'Consulta las compras consolidadas y agrupadas por proveedor.',
            endpoint: 'compras/proveedor',
            permission: REPORT_PERMISSIONS.COMPRAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', proveedorId: '' },
            refreshInterval: 60000,
            summary: [{ key: 'compras', label: 'Compras', type: 'number', color: '#3498db' }, { key: 'total_comprado', label: 'Total comprado', type: 'currency', color: '#e67e22' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.proveedorId],
            columns: [
                { key: 'proveedor_nombre', label: 'Proveedor' }, { key: 'compras', label: 'Compras', type: 'number', align: 'right' }, { key: 'total_comprado', label: 'Total comprado', type: 'currency', align: 'right' },
            ],
        }),
        'ingresos-mercaderia': createReport({
            id: 'ingresos-mercaderia',
            category: 'compras',
            title: 'Ingresos de mercadería',
            shortTitle: 'Ingresos',
            description: 'Consulta los ingresos de mercadería registrados por fechas.',
            endpoint: 'ingresos/mercaderia',
            permission: REPORT_PERMISSIONS.COMPRAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', proveedorId: '', estado: '' },
            refreshInterval: 60000,
            summary: [{ key: 'ingresos', label: 'Ingresos', type: 'number', color: '#3498db' }, { key: 'total', label: 'Total', type: 'currency', color: '#27ae60' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.proveedorId, filters.estado],
            columns: [
                { key: 'id_personalizado', label: 'Código' }, { key: 'numero_factura', label: 'Factura' }, { key: 'proveedor_nombre', label: 'Proveedor' },
                { key: 'fecha', label: 'Fecha', type: 'date' }, { key: 'estado', label: 'Estado' }, { key: 'total', label: 'Total', type: 'currency', align: 'right' },
            ],
        }),
        'egresos-mercaderia': createReport({
            id: 'egresos-mercaderia',
            category: 'compras',
            title: 'Egresos de mercadería',
            shortTitle: 'Egresos',
            description: 'Consulta las salidas de mercadería registradas por fechas.',
            endpoint: 'egresos/mercaderia',
            permission: REPORT_PERMISSIONS.COMPRAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', sucursalId: '', usuarioId: '' },
            refreshInterval: 60000,
            summary: [{ key: 'egresos', label: 'Egresos', type: 'number', color: '#e74c3c' }, { key: 'costo_total', label: 'Costo total', type: 'currency', color: '#e67e22' }],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.sucursalId, filters.usuarioId],
            columns: [
                { key: 'fecha', label: 'Fecha', type: 'datetime' }, { key: 'motivo', label: 'Motivo' }, { key: 'descripcion', label: 'Descripción' },
                { key: 'usuario_nombre', label: 'Usuario' }, { key: 'sucursal_nombre', label: 'Sucursal' }, { key: 'costo_total', label: 'Costo total', type: 'currency', align: 'right' },
            ],
        }),
    },
    caja: {
        'flujo-caja': createReport({
            id: 'flujo-caja',
            category: 'caja',
            title: 'Flujo de caja',
            shortTitle: 'Flujo de caja',
            description: 'Consulta los ingresos y egresos registrados en las cajas.',
            endpoint: 'caja/flujo',
            permission: REPORT_PERMISSIONS.CAJA,
            defaultFilters: { fechaDesde: '', fechaHasta: '', tipoCaja: '', tipo: '' },
            refreshInterval: 30000,
            summary: [{ key: 'ingresos', label: 'Ingresos', type: 'currency', color: '#27ae60' }, { key: 'egresos', label: 'Egresos', type: 'currency', color: '#e74c3c' }],
            filters: [filters.fechaDesde, filters.fechaHasta, { key: 'tipoCaja', label: 'Tipo de caja', type: 'select', queryParam: 'tipoCaja' }, { key: 'tipo', label: 'Tipo de movimiento', type: 'select', queryParam: 'tipo' }],
            columns: [
                { key: 'fecha', label: 'Fecha', type: 'datetime' }, { key: 'tipo_caja', label: 'Caja' }, { key: 'tipo', label: 'Tipo' }, { key: 'descripcion', label: 'Descripción' },
                { key: 'usuario_nombre', label: 'Usuario' }, { key: 'monto', label: 'Monto', type: 'currency', align: 'right' },
            ],
        }),
    },
    dashboard: {
        'dashboard-indicadores': createReport({
            id: 'dashboard-indicadores',
            category: 'dashboard',
            title: 'Dashboard de indicadores',
            shortTitle: 'Indicadores',
            description: 'Consulta un resumen consolidado de inventario, ventas, cartera y caja.',
            endpoint: 'dashboard/indicadores',
            permission: REPORT_PERMISSIONS.DASHBOARD,
            defaultFilters: { fechaDesde: '', fechaHasta: '' },
            refreshInterval: 30000,
            view: 'dashboard',
            summary: [
                { key: 'productos', label: 'Productos', type: 'number', color: '#3498db' }, { key: 'unidades_stock', label: 'Unidades en stock', type: 'number', color: '#1abc9c' },
                { key: 'ventas', label: 'Ventas', type: 'number', color: '#8e44ad' }, { key: 'total_ventas', label: 'Total vendido', type: 'currency', color: '#27ae60' },
                { key: 'cuentas_por_cobrar', label: 'Cuentas por cobrar', type: 'currency', color: '#e74c3c' }, { key: 'flujo_neto', label: 'Flujo neto', type: 'currency', color: '#f39c12' },
            ],
            filters: [filters.fechaDesde, filters.fechaHasta],
        }),
    },
};

export default reportsConfig;