import { REPORT_PERMISSIONS } from './categories.config';

const filters = {
    fechaDesde: { key: 'fechaDesde', label: 'Fecha desde', type: 'date', queryParam: 'fechaDesde' },
    fechaHasta: { key: 'fechaHasta', label: 'Fecha hasta', type: 'date', queryParam: 'fechaHasta' },
    codigo: { key: 'codigo', label: 'Producto', type: 'product-search', source: 'productos', queryParam: 'codigo' },
    grupo: { key: 'grupo', label: 'Grupo', type: 'entity', source: 'grupos', queryParam: 'grupo' },
    proveedorId: { key: 'proveedorId', label: 'Proveedor', type: 'entity', source: 'proveedores', queryParam: 'proveedorId' },
    sucursalId: { key: 'sucursalId', label: 'Sucursal', type: 'entity', source: 'sucursales', queryParam: 'sucursalId' },
    usuarioId: { key: 'usuarioId', label: 'Usuario', type: 'entity', source: 'usuarios', queryParam: 'usuarioId' },
    clienteId: { key: 'clienteId', label: 'Cliente', type: 'entity', source: 'clientes', queryParam: 'clienteId' },
    estado: {
        key: 'estado',
        label: 'Estado',
        type: 'select',
        queryParam: 'estado',
        options: [
            { value: '', label: 'Todos' },
            { value: 'PAGADA', label: 'Pagada' },
            { value: 'PENDIENTE', label: 'Pendiente' },
            { value: 'ANULADA', label: 'Anulada' },
        ],
    },
    tipoMovimiento: {
        key: 'tipoMovimiento',
        label: 'Tipo de movimiento',
        type: 'select',
        queryParam: 'tipoMovimiento',
        options: [
            { value: '', label: 'Todos' },
            { value: 'INVENTARIO_INICIAL', label: 'Inventario inicial' },
            { value: 'COMPRA', label: 'Compra' },
            { value: 'VENTA', label: 'Venta' },
            { value: 'DEVOLUCION_CLIENTE', label: 'Devolución de cliente' },
            { value: 'DEVOLUCION_PROVEEDOR', label: 'Devolución a proveedor' },
            { value: 'EGRESO', label: 'Egreso' },
            { value: 'AJUSTE', label: 'Ajuste' },
            { value: 'TRANSFERENCIA_ENTRADA', label: 'Transferencia de entrada' },
            { value: 'TRANSFERENCIA_SALIDA', label: 'Transferencia de salida' },
            { value: 'ANULACION_VENTA', label: 'Anulación de venta' },
            { value: 'ANULACION_COMPRA', label: 'Anulación de compra' },
            { value: 'ANULACION_EGRESO', label: 'Anulación de egreso' },
            { value: 'REVALORIZACION', label: 'Revalorización' },
            { value: 'COMPENSACION', label: 'Compensación' },
        ],
    },
};

const createReport = report => ({
    enabled: true,
    beta: false,
    rememberFilters: true,
    exportable: { pdf: true, excel: true, csv: false },
    actions: ['refresh', 'exportExcel', 'exportPdf', 'clearFilters'],
    summary: [],
    refreshInterval: null,
    filters: [],
    columns: [],
    ...report,
});

export const reportsConfig = {
    inventario: {
        kardex: createReport({
            id: 'kardex',
            category: 'inventario',
            title: 'Kardex',
            shortTitle: 'Kardex',
            description: 'Consulta todos los movimientos del inventario y filtra opcionalmente por producto.',
            endpoint: 'kardex/fecha',
            permission: REPORT_PERMISSIONS.INVENTARIO,
            defaultFilters: { codigo: '', grupo: '', proveedorId: '', usuarioId: '', tipoMovimiento: '', sucursalId: '', fechaDesde: '', fechaHasta: '' },
            summary: [
                { key: 'stockActual', label: 'Stock actual', type: 'number', color: '#1abc9c' },
                { key: 'entradas', label: 'Entradas', type: 'number', color: '#27ae60' },
                { key: 'salidas', label: 'Salidas', type: 'number', color: '#e74c3c' },
                { key: 'costoPromedio', label: 'Costo promedio', type: 'currency', color: '#8e44ad' },
                { key: 'valorInventario', label: 'Valor del inventario', type: 'currency', color: '#f39c12' },
                { key: 'ultimoMovimiento', label: 'Último movimiento', type: 'datetime', color: '#607d8b' },
            ],
            filters: [filters.codigo, filters.grupo, filters.proveedorId, filters.usuarioId, filters.tipoMovimiento, filters.sucursalId, filters.fechaDesde, filters.fechaHasta],
            productFields: [
                { key: 'codigo', label: 'Código' },
                { key: 'modelo', label: 'Modelo' },
                { key: 'color', label: 'Color' },
                { key: 'grupo', label: 'Grupo' },
                { key: 'costo', label: 'Costo', type: 'currency' },
                { key: 'pvp1', label: 'Precio venta', type: 'currency' },
                { key: 'stock', label: 'Stock actual', type: 'number' },
                { key: 'proveedor', label: 'Proveedor' },
                { key: 'ultimoIngreso', label: 'Último ingreso', type: 'datetime' },
                { key: 'estado', label: 'Estado' },
            ],
            columns: [
                { key: 'fecha', label: 'Fecha' },
                { key: 'hora', label: 'Hora' },
                { key: 'productoCodigo', label: 'Código' },
                { key: 'productoNombre', label: 'Producto' },
                { key: 'grupo', label: 'Grupo' },
                { key: 'documento', label: 'Documento' },
                { key: 'tipoMovimiento', label: 'Tipo de movimiento' },
                { key: 'detalle', label: 'Detalle' },
                { key: 'entrada', label: 'Entrada', type: 'number', align: 'right' },
                { key: 'salida', label: 'Salida', type: 'number', align: 'right' },
                { key: 'stockAnterior', label: 'Stock anterior', type: 'number', align: 'right' },
                { key: 'stockActual', label: 'Stock actual', type: 'number', align: 'right' },
                { key: 'costoUnitario', label: 'Costo unitario', type: 'currency', align: 'right' },
                { key: 'saldo', label: 'Saldo', type: 'currency', align: 'right' },
                { key: 'usuario', label: 'Usuario' },
                { key: 'sucursal', label: 'Sucursal' },
                { key: 'observacion', label: 'Observación' },
            ],
        }),
    },
    ventas: {
        'analisis-ventas': createReport({
            id: 'analisis-ventas',
            category: 'ventas',
            title: 'Análisis de Ventas',
            shortTitle: 'Análisis',
            description: 'Analiza ventas, cobros, agrupaciones y utilidad desde una sola pantalla.',
            endpoint: 'ventas/general',
            permission: REPORT_PERMISSIONS.VENTAS,
            defaultFilters: {
                fechaDesde: '',
                fechaHasta: '',
                clienteId: '',
                usuarioId: '',
                sucursalId: '',
                estado: '',
                metodoPago: '',
                buscarFactura: '',
                buscarCliente: '',
                tipoTransaccion: 'TODAS',
                vista: 'DETALLE',
            },
            refreshInterval: 60000,
            transactionTypes: [
                { value: 'TODAS', label: 'Todas las transacciones' },
                { value: 'VENTAS', label: 'Ventas (Facturas)' },
                { value: 'COBROS', label: 'Pago de deudas' },
                { value: 'VENTAS_COBROS', label: 'Ventas + Cobros' },
            ],
            views: [
                { value: 'DETALLE', label: 'Detalle' },
                { value: 'CLIENTE', label: 'Agrupado por cliente' },
                { value: 'USUARIO', label: 'Agrupado por usuario' },
                { value: 'SUCURSAL', label: 'Agrupado por sucursal' },
                { value: 'UTILIDAD', label: 'Utilidad' },
            ],
            filters: [
                filters.fechaDesde,
                filters.fechaHasta,
                filters.clienteId,
                filters.usuarioId,
                filters.sucursalId,
                filters.estado,
                { key: 'buscarFactura', label: 'Buscar factura', type: 'text', queryParam: 'buscarFactura' },
                { key: 'buscarCliente', label: 'Buscar cliente', type: 'text', queryParam: 'buscarCliente' },
            ],
        }),
    },
    /*
    compras: {
        'egresos-mercaderia': createReport({
            id: 'egresos-mercaderia',
            category: 'compras',
            title: 'Egresos de mercadería',
            shortTitle: 'Egresos',
            description: 'Consulta las salidas de mercadería registradas por fechas.',
            endpoint: 'egresos/mercaderia',
            permission: REPORT_PERMISSIONS.COMPRAS,
            defaultFilters: { fechaDesde: '', fechaHasta: '', sucursalId: '', usuarioId: '' },
            refreshInterval: 60000,
            summary: [
                { key: 'egresos', label: 'Egresos', type: 'number', color: '#e74c3c' },
                { key: 'costo_total', label: 'Costo total', type: 'currency', color: '#e67e22' },
            ],
            filters: [filters.fechaDesde, filters.fechaHasta, filters.sucursalId, filters.usuarioId],
            columns: [
                { key: 'fecha', label: 'Fecha', type: 'datetime' },
                { key: 'motivo', label: 'Motivo' },
                { key: 'descripcion', label: 'Descripción' },
                { key: 'usuario_nombre', label: 'Usuario' },
                { key: 'sucursal_nombre', label: 'Sucursal' },
                { key: 'costo_total', label: 'Costo total', type: 'currency', align: 'right' },
            ],
        }),
    },
    */
};

export default reportsConfig;